export const PLATFORMS = [
  "Switch",
  "Switch2",
  "iOS",
  "Android",
  "PC",
  "PS5",
] as const;

export type Platform = (typeof PLATFORMS)[number];

export const GENRES = [
  "ガチャRPG",
  "サバイバル",
  "アクション",
  "パズル",
  "育成",
  "スポーツ",
  "シューター",
  "アドベンチャー",
  "シミュレーション",
] as const;

export type Genre = (typeof GENRES)[number];
export type SortKey = "popular" | "newest" | "rating" | "playtime_asc" | "f2p";
export type ViewMode = "grid" | "list";
export type GachaFilter = "all" | "gacha" | "nogacha";

export type SearchGame = {
  id: number;
  title: string;
  developer: string;
  genre: Genre;
  platforms: Platform[];
  rating: number;
  ratingCount: number;
  avgPlaytime: number;
  releaseYear: number;
  price: number;
  isFree: boolean;
  hasGacha: boolean;
  f2pScore: number;
  volumeScore: number;
  img: string;
  tags: string[];
  popular: boolean;
};

export type SearchFilters = {
  platforms: Platform[];
  genres: Genre[];
  minRating: number;
  minF2P: number;
  freeOnly: boolean;
  hasGachaFilter: GachaFilter;
  maxPlaytime: number;
};

export const DEFAULT_FILTERS: SearchFilters = {
  platforms: [],
  genres: [],
  minRating: 0,
  minF2P: 0,
  freeOnly: false,
  hasGachaFilter: "all",
  maxPlaytime: 1000,
};

export const HW_SEARCH_HREF: Record<string, string> = {
  switch: "/games?platform=Switch",
  ios: "/games?platform=iOS",
  android: "/games?platform=Android",
  ps5: "/games?platform=PS5",
  pc: "/games?platform=PC",
  gacha: "/games?gacha=gacha",
};

export const SEARCH_GAMES: SearchGame[] = [
  {
    id: 1,
    title: "ウマ娘 プリティーダービー",
    developer: "Cygames",
    genre: "ガチャRPG",
    platforms: ["iOS", "Android"],
    rating: 4.3,
    ratingCount: 12800,
    avgPlaytime: 200,
    releaseYear: 2021,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 2,
    volumeScore: 5,
    img: "/games/umamusume.jpg",
    tags: ["ガチャあり", "育成", "競馬"],
    popular: true,
  },
  {
    id: 2,
    title: "プロセカ",
    developer: "Colorful Palette",
    genre: "ガチャRPG",
    platforms: ["iOS", "Android"],
    rating: 4.5,
    ratingCount: 9200,
    avgPlaytime: 300,
    releaseYear: 2020,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 3,
    volumeScore: 5,
    img: "/games/pjsekai.jpg",
    tags: ["ガチャあり", "音楽", "リズム"],
    popular: true,
  },
  {
    id: 3,
    title: "荒野行動",
    developer: "NetEase Games",
    genre: "サバイバル",
    platforms: ["iOS", "Android", "Switch"],
    rating: 4.1,
    ratingCount: 7400,
    avgPlaytime: 500,
    releaseYear: 2017,
    price: 0,
    isFree: true,
    hasGacha: false,
    f2pScore: 4,
    volumeScore: 5,
    img: "/games/koware.jpg",
    tags: ["バトルロイヤル", "無課金OK", "対戦"],
    popular: true,
  },
  {
    id: 4,
    title: "ポケモンGO",
    developer: "Niantic",
    genre: "アドベンチャー",
    platforms: ["iOS", "Android"],
    rating: 4.2,
    ratingCount: 18000,
    avgPlaytime: 800,
    releaseYear: 2016,
    price: 0,
    isFree: true,
    hasGacha: false,
    f2pScore: 4,
    volumeScore: 5,
    img: "/games/pokemon-go.jpg",
    tags: ["位置情報", "コレクション", "外出"],
    popular: true,
  },
  {
    id: 5,
    title: "スプラトゥーン3",
    developer: "任天堂",
    genre: "シューター",
    platforms: ["Switch"],
    rating: 4.6,
    ratingCount: 6100,
    avgPlaytime: 80,
    releaseYear: 2022,
    price: 6578,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/splatoon3.jpg",
    tags: ["対戦", "買い切り", "ファミリー"],
    popular: true,
  },
  {
    id: 6,
    title: "あつまれ どうぶつの森",
    developer: "任天堂",
    genre: "シミュレーション",
    platforms: ["Switch"],
    rating: 4.7,
    ratingCount: 8900,
    avgPlaytime: 300,
    releaseYear: 2020,
    price: 6578,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 5,
    img: "/games/animal-crossing.jpg",
    tags: ["まったり", "買い切り", "癒し"],
    popular: true,
  },
  {
    id: 7,
    title: "モンスターハンターNow",
    developer: "Niantic / カプコン",
    genre: "アクション",
    platforms: ["iOS", "Android"],
    rating: 4.0,
    ratingCount: 5300,
    avgPlaytime: 400,
    releaseYear: 2023,
    price: 0,
    isFree: true,
    hasGacha: false,
    f2pScore: 3,
    volumeScore: 4,
    img: "/games/mh-now.jpg",
    tags: ["位置情報", "狩りゲー", "アクション"],
    popular: false,
  },
  {
    id: 8,
    title: "原神",
    developer: "miHoYo",
    genre: "アクション",
    platforms: ["iOS", "Android", "PC", "PS5"],
    rating: 4.4,
    ratingCount: 22000,
    avgPlaytime: 500,
    releaseYear: 2020,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 3,
    volumeScore: 5,
    img: "/games/genshin.jpg",
    tags: ["ガチャあり", "オープンワールド", "高品質"],
    popular: true,
  },
  {
    id: 9,
    title: "パズドラ",
    developer: "ガンホー",
    genre: "パズル",
    platforms: ["iOS", "Android"],
    rating: 4.2,
    ratingCount: 14000,
    avgPlaytime: 1000,
    releaseYear: 2012,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 3,
    volumeScore: 5,
    img: "/games/pazudora.jpg",
    tags: ["ガチャあり", "パズル", "長寿タイトル"],
    popular: false,
  },
  {
    id: 10,
    title: "マインクラフト",
    developer: "Mojang",
    genre: "サバイバル",
    platforms: ["iOS", "Android", "Switch"],
    rating: 4.8,
    ratingCount: 15000,
    avgPlaytime: 1000,
    releaseYear: 2011,
    price: 840,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 5,
    img: "/games/minecraft.jpg",
    tags: ["クラフト", "買い切り", "子供OK"],
    popular: true,
  },
  {
    id: 11,
    title: "モンスト",
    developer: "MIXI",
    genre: "アクション",
    platforms: ["iOS", "Android"],
    rating: 4.3,
    ratingCount: 11000,
    avgPlaytime: 600,
    releaseYear: 2013,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 3,
    volumeScore: 5,
    img: "/games/monst.jpg",
    tags: ["ガチャあり", "協力プレイ", "長寿"],
    popular: false,
  },
  {
    id: 12,
    title: "ポケモン スカーレット・バイオレット",
    developer: "任天堂 / Game Freak",
    genre: "アドベンチャー",
    platforms: ["Switch"],
    rating: 4.1,
    ratingCount: 7200,
    avgPlaytime: 35,
    releaseYear: 2022,
    price: 6578,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/pokemon-go.jpg",
    tags: ["オープンワールド", "買い切り", "コレクション"],
    popular: true,
  },
  {
    id: 13,
    title: "Apex Legends Mobile",
    developer: "EA / Respawn",
    genre: "シューター",
    platforms: ["iOS", "Android"],
    rating: 4.2,
    ratingCount: 6800,
    avgPlaytime: 400,
    releaseYear: 2022,
    price: 0,
    isFree: true,
    hasGacha: false,
    f2pScore: 4,
    volumeScore: 5,
    img: "/games/apex.jpg",
    tags: ["バトルロイヤル", "FPS", "無課金OK"],
    popular: false,
  },
  {
    id: 14,
    title: "ツムツム",
    developer: "LINE / Disney",
    genre: "パズル",
    platforms: ["iOS", "Android"],
    rating: 4.4,
    ratingCount: 9500,
    avgPlaytime: 200,
    releaseYear: 2014,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 4,
    volumeScore: 4,
    img: "/games/tsumtsum.jpg",
    tags: ["ガチャあり", "カジュアル", "Disney"],
    popular: false,
  },
  {
    id: 15,
    title: "マリオカート8 デラックス",
    developer: "任天堂",
    genre: "スポーツ",
    platforms: ["Switch"],
    rating: 4.8,
    ratingCount: 10200,
    avgPlaytime: 50,
    releaseYear: 2017,
    price: 6578,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/mariokart.jpg",
    tags: ["レース", "買い切り", "ファミリー"],
    popular: true,
  },
  {
    id: 16,
    title: "ドラゴンクエストウォーク",
    developer: "スクウェア・エニックス",
    genre: "ガチャRPG",
    platforms: ["iOS", "Android"],
    rating: 4.1,
    ratingCount: 8100,
    avgPlaytime: 600,
    releaseYear: 2019,
    price: 0,
    isFree: true,
    hasGacha: true,
    f2pScore: 3,
    volumeScore: 5,
    img: "/games/dqwalk.jpg",
    tags: ["位置情報", "ガチャあり", "RPG"],
    popular: false,
  },
  {
    id: 17,
    title: "マリオカート ワールド",
    developer: "任天堂",
    genre: "スポーツ",
    platforms: ["Switch2"],
    rating: 4.7,
    ratingCount: 3200,
    avgPlaytime: 60,
    releaseYear: 2025,
    price: 9878,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/mariokart.jpg",
    tags: ["レース", "Switch2専用", "ファミリー"],
    popular: true,
  },
  {
    id: 18,
    title: "ゼルダの伝説 エコーズ オブ ウィズダム",
    developer: "任天堂",
    genre: "アドベンチャー",
    platforms: ["Switch", "Switch2"],
    rating: 4.6,
    ratingCount: 2800,
    avgPlaytime: 30,
    releaseYear: 2024,
    price: 6578,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/zelda-echoes.jpg",
    tags: ["買い切り", "パズル", "アクション"],
    popular: false,
  },
  {
    id: 19,
    title: "ブレイブリーデフォルト フライングフェアリー HD",
    developer: "スクウェア・エニックス",
    genre: "アドベンチャー",
    platforms: ["Switch2"],
    rating: 4.3,
    ratingCount: 1400,
    avgPlaytime: 50,
    releaseYear: 2025,
    price: 7678,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 4,
    img: "/games/bravely.jpg",
    tags: ["JRPG", "Switch2", "買い切り"],
    popular: false,
  },
  {
    id: 20,
    title: "モンスターハンターワイルズ",
    developer: "カプコン",
    genre: "アクション",
    platforms: ["PS5", "PC"],
    rating: 4.6,
    ratingCount: 892,
    avgPlaytime: 120,
    releaseYear: 2025,
    price: 8980,
    isFree: false,
    hasGacha: false,
    f2pScore: 5,
    volumeScore: 5,
    img: "/games/mh-wilds.jpg",
    tags: ["狩りゲー", "買い切り", "アクション"],
    popular: true,
  },
  {
    id: 21,
    title: "Call of Duty Warzone Mobile",
    developer: "Activision",
    genre: "シューター",
    platforms: ["iOS", "Android"],
    rating: 4.1,
    ratingCount: 1654,
    avgPlaytime: 200,
    releaseYear: 2024,
    price: 0,
    isFree: true,
    hasGacha: false,
    f2pScore: 4,
    volumeScore: 4,
    img: "/games/splatoon3.jpg",
    tags: ["バトルロイヤル", "FPS", "無課金寄り"],
    popular: false,
  },
];

export const SORT_OPTIONS: { value: SortKey; label: string }[] = [
  { value: "popular", label: "人気順" },
  { value: "newest", label: "新着順" },
  { value: "rating", label: "評価順" },
  { value: "f2p", label: "無課金遊びやすさ順" },
  { value: "playtime_asc", label: "プレイ時間（短い順）" },
];

export const PLATFORM_BADGE: Record<
  Platform,
  { color: string; bg: string; border: string; label: string }
> = {
  Switch: { color: "#DC2626", bg: "#FEF2F2", border: "#FECACA", label: "Switch" },
  Switch2: {
    color: "#B91C1C",
    bg: "#FFF1F1",
    border: "#FCA5A5",
    label: "Switch 2",
  },
  iOS: { color: "#374151", bg: "#F3F4F6", border: "#D1D5DB", label: "iOS" },
  Android: { color: "#15803D", bg: "#F0FDF4", border: "#BBF7D0", label: "Android" },
  PC: { color: "#2563EB", bg: "#EFF6FF", border: "#BFDBFE", label: "PC" },
  PS5: { color: "#1D4ED8", bg: "#EFF6FF", border: "#BFDBFE", label: "PS5" },
};

export function parsePlatforms(value?: string): Platform[] {
  if (!value) return [];
  return value
    .split(",")
    .map((item) => item.trim())
    .filter((item): item is Platform =>
      (PLATFORMS as readonly string[]).includes(item),
    );
}

export function parseGacha(value?: string): GachaFilter {
  if (value === "gacha" || value === "nogacha") return value;
  return "all";
}
