export const HW_QUICK = [
  { id: "switch", label: "Nintendo Switch", icon: "🎮", color: "#e53e3e", bg: "#fff5f5" },
  { id: "ios", label: "iOS / iPhone", icon: "📱", color: "#3182ce", bg: "#ebf8ff" },
  { id: "android", label: "Android", icon: "🤖", color: "#38a169", bg: "#f0fff4" },
  { id: "ps5", label: "PlayStation 5", icon: "🕹️", color: "#2d3748", bg: "#f7fafc" },
  { id: "pc", label: "Steam / PC", icon: "💻", color: "#d69e2e", bg: "#fffff0" },
  { id: "gacha", label: "ガチャゲー", icon: "✨", color: "#805ad5", bg: "#faf5ff" },
] as const;

export const FEATURED_GAMES = [
  {
    id: 1,
    title: "ゼルダの伝説\nエコーズ オブ ウィズダム",
    platform: "Switch",
    genre: "アクションRPG",
    rating: 4.8,
    reviewCount: 1243,
    tag: "注目作",
    tagColor: "#5c4dff",
    freeToPlay: false,
    playtime: "40〜60h",
    f2pScore: null,
    img: "/games/zelda-echoes.jpg",
  },
  {
    id: 2,
    title: "モンスターハンター\nワイルズ",
    platform: "Switch / PS5",
    genre: "アクション",
    rating: 4.6,
    reviewCount: 892,
    tag: "新着",
    tagColor: "#ff4d84",
    freeToPlay: false,
    playtime: "100h+",
    f2pScore: null,
    img: "/games/mh-wilds.jpg",
  },
  {
    id: 3,
    title: "ウマ娘\nプリティーダービー",
    platform: "スマホ",
    genre: "ガチャ育成",
    rating: 4.3,
    reviewCount: 3821,
    tag: "無課金OK",
    tagColor: "#10b981",
    freeToPlay: true,
    playtime: "∞",
    f2pScore: 3.5,
    img: "/games/umamusume.jpg",
  },
  {
    id: 4,
    title: "スプラトゥーン3",
    platform: "Switch",
    genre: "シューター",
    rating: 4.4,
    reviewCount: 2104,
    tag: "サバゲー",
    tagColor: "#f59e0b",
    freeToPlay: false,
    playtime: "∞",
    f2pScore: null,
    img: "/games/splatoon3.jpg",
  },
  {
    id: 5,
    title: "プロジェクトセカイ\nカラフルステージ",
    platform: "スマホ",
    genre: "リズム・ガチャ",
    rating: 4.5,
    reviewCount: 2987,
    tag: "評価急上昇",
    tagColor: "#ec4899",
    freeToPlay: true,
    playtime: "∞",
    f2pScore: 4.0,
    img: "/games/pjsekai.jpg",
  },
  {
    id: 6,
    title: "Call of Duty\nWarzone Mobile",
    platform: "スマホ",
    genre: "サバゲー",
    rating: 4.1,
    reviewCount: 1654,
    tag: "サバゲー",
    tagColor: "#64748b",
    freeToPlay: true,
    playtime: "∞",
    f2pScore: 4.2,
    img: "/games/splatoon3.jpg",
  },
] as const;

export type FeaturedGame = (typeof FEATURED_GAMES)[number];
export type FeaturedFilter = "all" | "rising" | "f2p" | "sabage";

export const REVIEWS = [
  {
    id: 1,
    game: "ウマ娘 プリティーダービー",
    platform: "スマホ",
    user: "たけし★ゲーマー",
    av: "T",
    avColor: "#5c4dff",
    rating: 5,
    badge: "無課金勢",
    badgeColor: "#10b981",
    text: "月30〜40連分の石が貯まるので計画的に引けば無課金でも推しキャラを狙えます。育成のやり込み要素が深くて飽きません。",
    playtime: "300時間",
    time: "2時間前",
    helpful: 42,
  },
  {
    id: 2,
    game: "スプラトゥーン3",
    platform: "Switch",
    user: "ナワバリ職人",
    av: "N",
    avColor: "#f59e0b",
    rating: 4,
    badge: "やり込み勢",
    badgeColor: "#5c4dff",
    text: "フェスが頻繁にあって飽きない！ブキのバランスも改善されてきた。友達と遊ぶと最高に楽しい。",
    playtime: "800時間",
    time: "5時間前",
    helpful: 28,
  },
  {
    id: 3,
    game: "ゼルダの伝説 エコーズ",
    platform: "Switch",
    user: "はるか",
    av: "H",
    avColor: "#ff4d84",
    rating: 5,
    badge: "初心者",
    badgeColor: "#64748b",
    text: "ゼルダ初挑戦でも楽しめました！謎解きが程よく難しくて達成感があります。クリア後もやること山盛りです。",
    playtime: "55時間",
    time: "昨日",
    helpful: 35,
  },
  {
    id: 4,
    game: "モンスターハンターワイルズ",
    platform: "Switch / PS5",
    user: "攻略マスター",
    av: "A",
    avColor: "#10b981",
    rating: 4,
    badge: "ベテラン勢",
    badgeColor: "#e53e3e",
    text: "前作よりフィールドが広くて探索が楽しい。操作感が格段に上がってて新規でも入りやすい。",
    playtime: "120時間",
    time: "2日前",
    helpful: 19,
  },
] as const;

export const TRENDS = [
  { rank: 1, title: "ウマ娘 新育成シナリオ", change: "up", count: "8.2k" },
  { rank: 2, title: "スプラ3 新シーズン開幕", change: "up", count: "6.7k" },
  { rank: 3, title: "モンハン ワイルズ アプデ", change: "same", count: "5.1k" },
  { rank: 4, title: "ゼルダ エコーズ 攻略", change: "up", count: "4.8k" },
  { rank: 5, title: "ポケモン 新作リーク情報", change: "down", count: "3.9k" },
  { rank: 6, title: "プロセカ 新イベント開始", change: "up", count: "3.2k" },
] as const;

export const SEARCH_SUGGESTIONS = [
  "ウマ娘 無課金攻略",
  "スプラ3 最強ブキ",
  "ゼルダ エコーズ ボス攻略",
  "モンハン 初心者おすすめ",
  "ガチャゲー 課金不要",
] as const;

export const QUICK_TAGS = [
  "無課金",
  "サバゲー",
  "ガチャ",
  "2人プレイ",
  "やりこみ",
  "Switch",
] as const;
